 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/critters", type: :request do
  
  # Critter. As you add validations to Critter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Critter.create! valid_attributes
      get critters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      critter = Critter.create! valid_attributes
      get critter_url(critter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_critter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      critter = Critter.create! valid_attributes
      get edit_critter_url(critter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Critter" do
        expect {
          post critters_url, params: { critter: valid_attributes }
        }.to change(Critter, :count).by(1)
      end

      it "redirects to the created critter" do
        post critters_url, params: { critter: valid_attributes }
        expect(response).to redirect_to(critter_url(Critter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Critter" do
        expect {
          post critters_url, params: { critter: invalid_attributes }
        }.to change(Critter, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post critters_url, params: { critter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested critter" do
        critter = Critter.create! valid_attributes
        patch critter_url(critter), params: { critter: new_attributes }
        critter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the critter" do
        critter = Critter.create! valid_attributes
        patch critter_url(critter), params: { critter: new_attributes }
        critter.reload
        expect(response).to redirect_to(critter_url(critter))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        critter = Critter.create! valid_attributes
        patch critter_url(critter), params: { critter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested critter" do
      critter = Critter.create! valid_attributes
      expect {
        delete critter_url(critter)
      }.to change(Critter, :count).by(-1)
    end

    it "redirects to the critters list" do
      critter = Critter.create! valid_attributes
      delete critter_url(critter)
      expect(response).to redirect_to(critters_url)
    end
  end
end
